apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flexigym-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "api-gateway"
spec:
  rules:
  - http:
      paths:
      - path: /auth/
        backend:
          serviceName: web
          servicePort: 5000
      - path: /
        backend:
          serviceName: flexigym-angular-app
          servicePort: 8080
