language: python
sudo: required
python:
 - "3.4"
 - "3.5"
 - "3.6"
before_install:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
 - export VISORHOME=$TRAVIS_BUILD_DIR
install:
 - pip install -r requirements.txt
 - pip install coveralls
script:
 - coverage run setup.py test
after_success:
 - coveralls
