apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
#    cloud.google.com/load-balancer-type: "Internal"
  creationTimestamp: null
  labels:
    io.kompose.service: flexigym-subscribe-api
  name: flexigym-subscribe-api
spec:
  type: ClusterIP
#  loadBalancerIP: 10.148.0.11
  ports:
  - name: "6200"
    port: 6200
    targetPort: 5000
  selector:
    io.kompose.service: flexigym-subscribe-api
status:
  loadBalancer: {}
